# Generated by Django 4.1.2 on 2022-10-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='street_name',
        ),
    ]
